const video_objs = [{'date': 'Monday 7/8/2019 5:00 am',
'topic': 'WQU DS Module Introductory Video',
'href': 'https://youtu.be/QUQSY7pmuSQ',
'link_text': 'https://youtu.be/QUQSY7pmuSQ'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.1 Basic Programming & Variables',
'href': 'https://youtu.be/3phV29yvWO8',
'link_text': 'https://youtu.be/3phV29yvWO8'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.2 Functions',
'href': 'https://youtu.be/SytwpgZ5k6U',
'link_text': 'https://youtu.be/SytwpgZ5k6U'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.3 Logic & Conditional Expressions',
'href': 'https://youtu.be/CyjsNEFjLVk',
'link_text': 'https://youtu.be/CyjsNEFjLVk'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.4 Iteration',
'href': 'https://youtu.be/MIjqvWgfdq8',
'link_text': 'https://youtu.be/MIjqvWgfdq8'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.1 Data Structures (list)',
'href': 'https://youtu.be/GGhWL_r_CSE',
'link_text': 'https://youtu.be/GGhWL_r_CSE'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.2 Data Structures (tuple)',
'href': 'https://youtu.be/jDuGDuzGkyE',
'link_text': 'https://youtu.be/jDuGDuzGkyE'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.3 Data Structures (set)',
'href': 'https://youtu.be/b4odPCnUcwA',
'link_text': 'https://youtu.be/b4odPCnUcwA'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.4 Data Structures (dict)',
'href': 'https://youtu.be/Acv69ca9Bu8',
'link_text': 'https://youtu.be/Acv69ca9Bu8'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.5 Data Structures (collections module)',
'href': 'https://youtu.be/cS2xi4Ut0lY',
'link_text': 'https://youtu.be/cS2xi4Ut0lY'},
{'date': 'Monday 7/8/2019 5:00 pm',
'topic': 'Office Hour 1',
'href': 'https://www.youtube.com/watch?v=pEcBhR-YQF0',
'link_text': 'https://www.youtube.com/watch?v=pEcBhR-YQF0'},
{'date': 'Tuesday 7/9/2019 9:00 pm',
'topic': 'Office Hour 2',
'href': 'https://www.youtube.com/watch?v=qV5L_sIe-EU',
'link_text': 'https://www.youtube.com/watch?v=qV5L_sIe-EU'},
{'date': 'Wednesday 7/10/2019 5:00 pm',
'topic': 'Office Hour 3',
'href': 'https://www.youtube.com/watch?v=X9yJ1p7412Q',
'link_text': 'https://www.youtube.com/watch?v=X9yJ1p7412Q'},
{'date': 'Thursday 7/11/2019 9:00 pm',
'topic': 'Office Hour 4',
'href': 'https://www.youtube.com/watch?v=Sf9lW8Pc1lA',
'link_text': 'https://www.youtube.com/watch?v=Sf9lW8Pc1lA'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.1 Algorithms and Complexity Analysis',
'href': 'https://youtu.be/PL15zDN5cCA',
'link_text': 'https://youtu.be/PL15zDN5cCA'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.2 Computational/Time Complexity',
'href': 'https://youtu.be/X9O5vGqMl1s',
'link_text': 'https://youtu.be/X9O5vGqMl1s'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.3 Recursion & Memoization',
'href': 'https://youtu.be/8yaoYqokmPk',
'link_text': 'https://youtu.be/8yaoYqokmPk'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.4 Memory Complexity & Data Structures',
'href': 'https://youtu.be/RuPUm5nbNQY',
'link_text': 'https://youtu.be/RuPUm5nbNQY'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.1 What is an Object?',
'href': 'https://youtu.be/21Ia8yZtQqU',
'link_text': 'https://youtu.be/21Ia8yZtQqU'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.2 Introduction to Classes',
'href': 'https://youtu.be/wxNT_vPQihE',
'link_text': 'https://youtu.be/wxNT_vPQihE'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.3 Defining Useful Classes',
'href': 'https://youtu.be/Zi4DqsSXHUE',
'link_text': 'https://youtu.be/Zi4DqsSXHUE'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.4 Object-Oriented Programming & Inheritance',
'href': 'https://youtu.be/UxR8ZPTMkuc',
'link_text': 'https://youtu.be/UxR8ZPTMkuc'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.3.1 VC Miniproject Intro & Hackerrank Coding Challenges',
'href': 'https://youtu.be/k80mHM-VqBQ',
'link_text': 'https://youtu.be/k80mHM-VqBQ'},
{'date': 'Monday 7/15/2019 5:00 pm',
'topic': 'Office Hour 5',
'href': 'https://www.youtube.com/watch?v=xwKQdo5rg1o',
'link_text': 'https://www.youtube.com/watch?v=xwKQdo5rg1o'},
{'date': 'Tuesday 7/16/2019 9:00 pm',
'topic': 'Office Hour 6',
'href': 'https://www.youtube.com/watch?v=rorgobIEsSY',
'link_text': 'https://www.youtube.com/watch?v=rorgobIEsSY'},
{'date': 'Wednesday 7/17/2019 5:00 pm',
'topic': 'Office Hour 7',
'href': 'https://www.youtube.com/watch?v=CCe1EUc7yck',
'link_text': 'https://www.youtube.com/watch?v=CCe1EUc7yck'},
{'date': 'Thursday 7/18/2019 9:00 pm',
'topic': 'Office Hour 8',
'href': 'https://www.youtube.com/watch?v=9pzfOEoX1vE',
'link_text': 'https://www.youtube.com/watch?v=9pzfOEoX1vE'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.1.1 Pythonic Programming',
'href': 'https://youtu.be/20WhvoAQVIc',
'link_text': 'https://youtu.be/20WhvoAQVIc'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.1.2 Python Modules & Imports',
'href': 'https://youtu.be/9xdmBjurb7c',
'link_text': 'https://youtu.be/9xdmBjurb7c'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.1.3 Exceptions & Debugging',
'href': 'https://youtu.be/dvU2UY6QM5I',
'link_text': 'https://youtu.be/dvU2UY6QM5I'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.1 Basic Python IO',
'href': 'https://youtu.be/TCJktfMOaPw',
'link_text': 'https://youtu.be/TCJktfMOaPw'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.2 File System Operations in Python',
'href': 'https://youtu.be/_9BHLex7FC8',
'link_text': 'https://youtu.be/_9BHLex7FC8'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.3 CSV Files',
'href': 'https://youtu.be/kZiE5nZPH5E',
'link_text': 'https://youtu.be/kZiE5nZPH5E'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.4 JSON Files',
'href': 'https://youtu.be/fI0nOob4fuA',
'link_text': 'https://youtu.be/fI0nOob4fuA'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.5 Compression & GZip Files',
'href': 'https://youtu.be/Z3MQ8_zpczI',
'link_text': 'https://youtu.be/Z3MQ8_zpczI'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.6 Serialization & Pickle Files',
'href': 'https://youtu.be/uPwk_TbHGdY',
'link_text': 'https://youtu.be/uPwk_TbHGdY'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.3.1 PW Miniproject Intro',
'href': 'https://youtu.be/sCB8g4D-0DA',
'link_text': 'https://youtu.be/sCB8g4D-0DA'},
{'date': 'Monday 7/22/2019 5:00 pm',
'topic': 'Office Hour 9',
'href': 'https://www.youtube.com/watch?v=I1i-z1IVDf8',
'link_text': 'https://www.youtube.com/watch?v=I1i-z1IVDf8'},
{'date': 'Tuesday 7/23/2019 9:00 pm',
'topic': 'Office Hour 10',
'href': 'https://www.youtube.com/watch?v=f9LSr4AzSvY',
'link_text': 'https://www.youtube.com/watch?v=f9LSr4AzSvY'},
{'date': 'Wednesday 7/24/2019 5:00 pm',
'topic': 'Office Hour 11',
'href': 'https://www.youtube.com/watch?v=INffneZ0nig',
'link_text': 'https://www.youtube.com/watch?v=INffneZ0nig'},
{'date': 'Thursday 7/25/2019 9:00 pm',
'topic': 'Office Hour 12',
'href': 'https://www.youtube.com/watch?v=gaPI0y7tIgc',
'link_text': 'https://www.youtube.com/watch?v=gaPI0y7tIgc'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.1 Intro to NumPy',
'href': 'https://youtu.be/eI-7PDaWfPk',
'link_text': 'https://youtu.be/eI-7PDaWfPk'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.2 Creating NumPy Arrays',
'href': 'https://youtu.be/3gXD67pTVP4',
'link_text': 'https://youtu.be/3gXD67pTVP4'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.3 Advantages of NumPy',
'href': 'https://youtu.be/NOzCJa16gHw',
'link_text': 'https://youtu.be/NOzCJa16gHw'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.4 Computation with NumPy',
'href': 'https://youtu.be/QF9TQ9Yj6tc',
'link_text': 'https://youtu.be/QF9TQ9Yj6tc'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.5 Mutating NumPy Arrays',
'href': 'https://youtu.be/UPd2zcr5Tbc',
'link_text': 'https://youtu.be/UPd2zcr5Tbc'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.6 Plotting with Matplotlib',
'href': 'https://youtu.be/mRxAAcGRR2U',
'link_text': 'https://youtu.be/mRxAAcGRR2U'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.7 Intro to Pandas',
'href': 'https://youtu.be/zu4uCw79iRU',
'link_text': 'https://youtu.be/zu4uCw79iRU'},
{'date': 'Monday 7/29/2019 5:00 pm',
'topic': 'Office Hour 13',
'href': 'https://www.youtube.com/watch?v=yuZ58EYwfWc',
'link_text': 'https://www.youtube.com/watch?v=yuZ58EYwfWc'},
{'date': 'Tuesday 7/30/2019 9:00 pm',
'topic': 'Office Hour 14',
'href': 'https://www.youtube.com/watch?v=-1AitK6n2ts',
'link_text': 'https://www.youtube.com/watch?v=-1AitK6n2ts'},
{'date': 'Wednesday 7/31/2019 5:00 pm',
'topic': 'Office Hour 15',
'href': 'https://www.youtube.com/watch?v=Thi2X0AOaks',
'link_text': 'https://www.youtube.com/watch?v=Thi2X0AOaks'},
{'date': 'Thursday 8/1/2019 9:00 pm',
'topic': 'Office Hour 16',
'href': 'https://www.youtube.com/watch?v=cs5vMAjSaCI',
'link_text': 'https://www.youtube.com/watch?v=cs5vMAjSaCI'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.1 Pandas Overview',
'href': 'https://youtu.be/LLltyyJH9kk',
'link_text': 'https://youtu.be/LLltyyJH9kk'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.2 Pandas IO',
'href': 'https://youtu.be/KmmwUVrYMOQ',
'link_text': 'https://youtu.be/KmmwUVrYMOQ'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.3 Filtering DataFrames',
'href': 'https://youtu.be/EkCWEMe6cSg',
'link_text': 'https://youtu.be/EkCWEMe6cSg'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.4 Data Transformations',
'href': 'https://youtu.be/3HdYzqh8Bag',
'link_text': 'https://youtu.be/3HdYzqh8Bag'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.5 Data Aggregation',
'href': 'https://youtu.be/_93sDSezpD8',
'link_text': 'https://youtu.be/_93sDSezpD8'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.6 Joins & Multiple DataFrames',
'href': 'https://youtu.be/0QEgP-m8MFE',
'link_text': 'https://youtu.be/0QEgP-m8MFE'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.7 Time Series Data',
'href': 'https://youtu.be/WzIHzSet8WY',
'link_text': 'https://youtu.be/WzIHzSet8WY'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.1 Intro to Statistics',
'href': 'https://youtu.be/y54T0l8LilY',
'link_text': 'https://youtu.be/y54T0l8LilY'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.2 Estimating Means',
'href': 'https://youtu.be/qsDQHeqJuhw',
'link_text': 'https://youtu.be/qsDQHeqJuhw'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.3 Standard Error of the Mean',
'href': 'https://youtu.be/T_EC239eoM4',
'link_text': 'https://youtu.be/T_EC239eoM4'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.4 Hypothesis Testing & Z-Scores',
'href': 'https://youtu.be/FDOZK1DYh2w',
'link_text': 'https://youtu.be/FDOZK1DYh2w'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.5 Parameter Estimation & Confidence Intervals',
'href': 'https://youtu.be/W6fFG3x5-zE',
'link_text': 'https://youtu.be/W6fFG3x5-zE'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.3.1 DW Miniproject Intro',
'href': 'https://youtu.be/xgna885PXg0',
'link_text': 'https://youtu.be/xgna885PXg0'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': 'Extra Statistics Videos',
'href': 'https://www.youtube.com/playlist?list=PLVNgHN883b8FuKC-Fpnh72thE4m7J1nNO',
'link_text': 'https://www.youtube.com/playlist?list=PLVNgHN883b8FuKC-Fpnh72thE4m7J1nNO'},
{'date': 'Monday 8/5/2019 5:00 pm',
'topic': 'Office Hour 17',
'href': 'canceled',
'link_text': 'canceled'},
{'date': 'Tuesday 8/6/2019 9:00 pm',
'topic': 'Office Hour 18',
'href': 'https://youtu.be/AyciFXagRbs',
'link_text': 'https://youtu.be/AyciFXagRbs'},
{'date': 'Wednesday 8/7/2019 5:00 pm',
'topic': 'Office Hour 19',
'href': 'https://www.youtube.com/watch?v=cju9Pk-3kAc',
'link_text': 'https://www.youtube.com/watch?v=cju9Pk-3kAc'},
{'date': 'Thursday 8/8/2019 9:00 pm',
'topic': 'Office Hour 20',
'href': 'https://www.youtube.com/watch?v=cSVde7bxMKg',
'link_text': 'https://www.youtube.com/watch?v=cSVde7bxMKg'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.1 Data Munging & Web Scraping',
'href': 'https://youtu.be/wV4BU2caSOs',
'link_text': 'https://youtu.be/wV4BU2caSOs'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.2 Cleaning & Structing Data',
'href': 'https://youtu.be/dtAEkwMUWZk',
'link_text': 'https://youtu.be/dtAEkwMUWZk'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.3 Dealing with Multiple Data Sources',
'href': 'https://youtu.be/ci9AvvnON4g',
'link_text': 'https://youtu.be/ci9AvvnON4g'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.4 Data Munging in Pandas',
'href': 'https://youtu.be/1Y8e8UhsvME',
'link_text': 'https://youtu.be/1Y8e8UhsvME'},
{'date': 'Monday 8/12/2019 5:00 pm',
'topic': 'Office Hour 21',
'href': 'https://www.youtube.com/watch?v=KnOtFOARQ3w',
'link_text': 'https://www.youtube.com/watch?v=KnOtFOARQ3w'},
{'date': 'Tuesday 8/13/2019 9:00 pm',
'topic': 'Office Hour 22',
'href': 'https://www.youtube.com/watch?v=O9n6DY_fDXM',
'link_text': 'https://www.youtube.com/watch?v=O9n6DY_fDXM'},
{'date': 'Wednesday 8/14/2019 5:00 pm',
'topic': 'Office Hour 23',
'href': 'https://www.youtube.com/watch?v=bEv3mNfL_Ig',
'link_text': 'https://www.youtube.com/watch?v=bEv3mNfL_Ig'},
{'date': 'Thursday 8/15/2019 9:00 pm',
'topic': 'Office Hour 24',
'href': 'https://www.youtube.com/watch?v=IyjI7LfXyLE',
'link_text': 'https://www.youtube.com/watch?v=IyjI7LfXyLE'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.1 SQL & Relational Databases',
'href': 'https://youtu.be/1VkpuNpEqKA',
'link_text': 'https://youtu.be/1VkpuNpEqKA'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.2 Basic SQL Syntax',
'href': 'https://youtu.be/5i9OvFAPbAs',
'link_text': 'https://youtu.be/5i9OvFAPbAs'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.3 Filtering & Sorting Data in SQL',
'href': 'https://youtu.be/LEmp_AaIxGM',
'link_text': 'https://youtu.be/LEmp_AaIxGM'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.4 Joins & Aggregations in SQL',
'href': 'https://youtu.be/HLTotdjNvl4',
'link_text': 'https://youtu.be/HLTotdjNvl4'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.5 Comparison of SQL Flavors',
'href': 'https://youtu.be/PeGsrKiJRY8',
'link_text': 'https://youtu.be/PeGsrKiJRY8'},
{'date': 'Monday 8/19/2019 5:00 pm',
'topic': 'Office Hour 25',
'href': 'https://youtu.be/GtbbTSAk3-k',
'link_text': 'https://youtu.be/GtbbTSAk3-k'},
{'date': 'Tuesday 8/20/2019 9:00 pm',
'topic': 'Office Hour 26',
'href': 'https://www.youtube.com/watch?v=obQjp9zaK4M',
'link_text': 'https://www.youtube.com/watch?v=obQjp9zaK4M'},
{'date': 'Wednesday 8/21/2019 5:00 pm',
'topic': 'Office Hour 27',
'href': 'https://www.youtube.com/watch?v=ZP-l-sSS-Uk',
'link_text': 'https://www.youtube.com/watch?v=ZP-l-sSS-Uk'},
{'date': 'Thursday 8/22/2019 9:00 pm',
'topic': 'Office Hour 28',
'href': 'https://www.youtube.com/watch?v=aILirNMlE38',
'link_text': 'https://www.youtube.com/watch?v=aILirNMlE38'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.1 Introduction to Object Relation Mapping',
'href': 'https://youtu.be/ZkOCn4FWd0Q',
'link_text': 'https://youtu.be/ZkOCn4FWd0Q'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.2 Using Classes for Applications',
'href': 'https://youtu.be/unLMZzFsx1Q',
'link_text': 'https://youtu.be/unLMZzFsx1Q'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.3 Translating Classes into SQL with ORM',
'href': 'https://youtu.be/ZT0gt0F88Ks',
'link_text': 'https://youtu.be/ZT0gt0F88Ks'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.4 Pushing Objects to SQL & Making Queries',
'href': 'https://youtu.be/88UKnoER9lw',
'link_text': 'https://youtu.be/88UKnoER9lw'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.2.1 Course Conclusion',
'href': 'https://youtu.be/pAT_9CkcsU4',
'link_text': 'https://youtu.be/pAT_9CkcsU4'},
{'date': 'Monday 8/26/2019 5:00 pm',
'topic': 'Office Hour 29',
'href': 'https://www.youtube.com/watch?v=yptGfk0Lej8',
'link_text': 'https://www.youtube.com/watch?v=yptGfk0Lej8'},
{'date': 'Tuesday 8/27/2019 9:00 pm',
'topic': 'Office Hour 30',
'href': 'https://www.youtube.com/watch?v=GXNbrwYiEHg',
'link_text': 'https://www.youtube.com/watch?v=GXNbrwYiEHg'},
{'date': 'Wednesday 8/28/2019 5:00 pm',
'topic': 'Office Hour 31',
'href': 'https://www.youtube.com/watch?v=gU1rypGu_n4',
'link_text': 'https://www.youtube.com/watch?v=gU1rypGu_n4'},
{'date': 'Thursday 8/29/2019 9:00 pm',
'topic': 'Office Hour 32',
'href': 'https://www.youtube.com/watch?v=Ex2I9HnPZU8',
'link_text': 'https://www.youtube.com/watch?v=Ex2I9HnPZU8'}]

const table = document.createElement('table');
table.style.border = '1px solid';

table.style.borderCollapse = 'collapse';
const contents = document.getElementById('content');
const row = document.createElement('tr');
row.style.backgroundColor = 'darkgreen'
row.style.color = 'white';
for (field of ['Date', 'Event', 'Youtube Link']) {
  const header = document.createElement('th');
  header.style.height = '40px';
  header.innerHTML = field;
  row.appendChild(header)
}

const footerRow = document.createElement('tr');
footerRow.style.backgroundColor = 'darkgreen'
for (field of ['Date', 'Event', 'Youtube Link']) {
  const footer = document.createElement('th');
  footer.style.height = '40px';
  footer.innerHTML = '';
  footerRow.appendChild(footer)
}

table.appendChild(row);
for (i of video_objs) {
  const rows = document.createElement('tr');
  const fields = Object.keys(i);

  // remove the link_text field
  fields.pop()
  fields.forEach(key => {
    const cell = document.createElement('td');
    cell.style.border = '1px solid';
    cell.style.padding = '5px';
    if (key === 'href') {
      const anchor = document.createElement('a');
      anchor.innerHTML = i[key];
      anchor.href = i['href']
      cell.appendChild(anchor)
      anchor.style.color = 'white';
    } else {
      cell.innerHTML = i[key]
    }
    cell.style.backgroundColor = 'gray'
    cell.style.color = 'white';
    rows.appendChild(cell);
  })
  table.appendChild(rows)
};

table.appendChild(footerRow)
contents.appendChild(table);
