let videoObjs = [{'date': 'Monday 7/8/2019 5:00 am',
'topic': 'WQU DS Module Introductory Video',
'href': 'https://youtu.be/QUQSY7pmuSQ',
'link_text': 'https://youtu.be/QUQSY7pmuSQ'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.1 Basic Programming & Variables',
'href': 'https://youtu.be/3phV29yvWO8',
'link_text': 'https://youtu.be/3phV29yvWO8'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.2 Functions',
'href': 'https://youtu.be/SytwpgZ5k6U',
'link_text': 'https://youtu.be/SytwpgZ5k6U'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.3 Logic & Conditional Expressions',
'href': 'https://youtu.be/CyjsNEFjLVk',
'link_text': 'https://youtu.be/CyjsNEFjLVk'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.1.4 Iteration',
'href': 'https://youtu.be/MIjqvWgfdq8',
'link_text': 'https://youtu.be/MIjqvWgfdq8'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.1 Data Structures (list)',
'href': 'https://youtu.be/GGhWL_r_CSE',
'link_text': 'https://youtu.be/GGhWL_r_CSE'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.2 Data Structures (tuple)',
'href': 'https://youtu.be/jDuGDuzGkyE',
'link_text': 'https://youtu.be/jDuGDuzGkyE'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.3 Data Structures (set)',
'href': 'https://youtu.be/b4odPCnUcwA',
'link_text': 'https://youtu.be/b4odPCnUcwA'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.4 Data Structures (dict)',
'href': 'https://youtu.be/Acv69ca9Bu8',
'link_text': 'https://youtu.be/Acv69ca9Bu8'},
{'date': 'Monday 7/8/2019 5:00 am',
'topic': '1.2.5 Data Structures (collections module)',
'href': 'https://youtu.be/cS2xi4Ut0lY',
'link_text': 'https://youtu.be/cS2xi4Ut0lY'},
{'date': 'Monday 7/8/2019 5:00 pm',
'topic': 'Office Hour 1',
'href': 'https://www.youtube.com/watch?v=pEcBhR-YQF0',
'link_text': 'https://www.youtube.com/watch?v=pEcBhR-YQF0'},
{'date': 'Tuesday 7/9/2019 9:00 pm',
'topic': 'Office Hour 2',
'href': 'https://www.youtube.com/watch?v=qV5L_sIe-EU',
'link_text': 'https://www.youtube.com/watch?v=qV5L_sIe-EU'},
{'date': 'Wednesday 7/10/2019 5:00 pm',
'topic': 'Office Hour 3',
'href': 'https://www.youtube.com/watch?v=X9yJ1p7412Q',
'link_text': 'https://www.youtube.com/watch?v=X9yJ1p7412Q'},
{'date': 'Thursday 7/11/2019 9:00 pm',
'topic': 'Office Hour 4',
'href': 'https://www.youtube.com/watch?v=Sf9lW8Pc1lA',
'link_text': 'https://www.youtube.com/watch?v=Sf9lW8Pc1lA'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.1 Algorithms and Complexity Analysis',
'href': 'https://youtu.be/PL15zDN5cCA',
'link_text': 'https://youtu.be/PL15zDN5cCA'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.2 Computational/Time Complexity',
'href': 'https://youtu.be/X9O5vGqMl1s',
'link_text': 'https://youtu.be/X9O5vGqMl1s'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.3 Recursion & Memoization',
'href': 'https://youtu.be/8yaoYqokmPk',
'link_text': 'https://youtu.be/8yaoYqokmPk'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.1.4 Memory Complexity & Data Structures',
'href': 'https://youtu.be/RuPUm5nbNQY',
'link_text': 'https://youtu.be/RuPUm5nbNQY'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.1 What is an Object?',
'href': 'https://youtu.be/21Ia8yZtQqU',
'link_text': 'https://youtu.be/21Ia8yZtQqU'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.2 Introduction to Classes',
'href': 'https://youtu.be/wxNT_vPQihE',
'link_text': 'https://youtu.be/wxNT_vPQihE'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.3 Defining Useful Classes',
'href': 'https://youtu.be/Zi4DqsSXHUE',
'link_text': 'https://youtu.be/Zi4DqsSXHUE'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.2.4 Object-Oriented Programming & Inheritance',
'href': 'https://youtu.be/UxR8ZPTMkuc',
'link_text': 'https://youtu.be/UxR8ZPTMkuc'},
{'date': 'Monday 7/15/2019 5:00 am',
'topic': '2.3.1 VC Miniproject Intro & Hackerrank Coding Challenges',
'href': 'https://youtu.be/k80mHM-VqBQ',
'link_text': 'https://youtu.be/k80mHM-VqBQ'},
{'date': 'Monday 7/15/2019 5:00 pm',
'topic': 'Office Hour 5',
'href': 'https://www.youtube.com/watch?v=xwKQdo5rg1o',
'link_text': 'https://www.youtube.com/watch?v=xwKQdo5rg1o'},
{'date': 'Tuesday 7/16/2019 9:00 pm',
'topic': 'Office Hour 6',
'href': 'https://www.youtube.com/watch?v=rorgobIEsSY',
'link_text': 'https://www.youtube.com/watch?v=rorgobIEsSY'},
{'date': 'Wednesday 7/17/2019 5:00 pm',
'topic': 'Office Hour 7',
'href': 'https://www.youtube.com/watch?v=CCe1EUc7yck',
'link_text': 'https://www.youtube.com/watch?v=CCe1EUc7yck'},
{'date': 'Thursday 7/18/2019 9:00 pm',
'topic': 'Office Hour 8',
'href': 'https://www.youtube.com/watch?v=9pzfOEoX1vE',
'link_text': 'https://www.youtube.com/watch?v=9pzfOEoX1vE'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.1.1 Pythonic Programming',
'href': 'https://youtu.be/20WhvoAQVIc',
'link_text': 'https://youtu.be/20WhvoAQVIc'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.1.2 Python Modules & Imports',
'href': 'https://youtu.be/9xdmBjurb7c',
'link_text': 'https://youtu.be/9xdmBjurb7c'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.1.3 Exceptions & Debugging',
'href': 'https://youtu.be/dvU2UY6QM5I',
'link_text': 'https://youtu.be/dvU2UY6QM5I'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.1 Basic Python IO',
'href': 'https://youtu.be/TCJktfMOaPw',
'link_text': 'https://youtu.be/TCJktfMOaPw'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.2 File System Operations in Python',
'href': 'https://youtu.be/_9BHLex7FC8',
'link_text': 'https://youtu.be/_9BHLex7FC8'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.3 CSV Files',
'href': 'https://youtu.be/kZiE5nZPH5E',
'link_text': 'https://youtu.be/kZiE5nZPH5E'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.4 JSON Files',
'href': 'https://youtu.be/fI0nOob4fuA',
'link_text': 'https://youtu.be/fI0nOob4fuA'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.5 Compression & GZip Files',
'href': 'https://youtu.be/Z3MQ8_zpczI',
'link_text': 'https://youtu.be/Z3MQ8_zpczI'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.2.6 Serialization & Pickle Files',
'href': 'https://youtu.be/uPwk_TbHGdY',
'link_text': 'https://youtu.be/uPwk_TbHGdY'},
{'date': 'Sunday 7/21/2019 5:00 am',
'topic': '3.3.1 PW Miniproject Intro',
'href': 'https://youtu.be/sCB8g4D-0DA',
'link_text': 'https://youtu.be/sCB8g4D-0DA'},
{'date': 'Monday 7/22/2019 5:00 pm',
'topic': 'Office Hour 9',
'href': 'https://www.youtube.com/watch?v=I1i-z1IVDf8',
'link_text': 'https://www.youtube.com/watch?v=I1i-z1IVDf8'},
{'date': 'Tuesday 7/23/2019 9:00 pm',
'topic': 'Office Hour 10',
'href': 'https://www.youtube.com/watch?v=f9LSr4AzSvY',
'link_text': 'https://www.youtube.com/watch?v=f9LSr4AzSvY'},
{'date': 'Wednesday 7/24/2019 5:00 pm',
'topic': 'Office Hour 11',
'href': 'https://www.youtube.com/watch?v=INffneZ0nig',
'link_text': 'https://www.youtube.com/watch?v=INffneZ0nig'},
{'date': 'Thursday 7/25/2019 9:00 pm',
'topic': 'Office Hour 12',
'href': 'https://www.youtube.com/watch?v=gaPI0y7tIgc',
'link_text': 'https://www.youtube.com/watch?v=gaPI0y7tIgc'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.1 Intro to NumPy',
'href': 'https://youtu.be/eI-7PDaWfPk',
'link_text': 'https://youtu.be/eI-7PDaWfPk'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.2 Creating NumPy Arrays',
'href': 'https://youtu.be/3gXD67pTVP4',
'link_text': 'https://youtu.be/3gXD67pTVP4'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.3 Advantages of NumPy',
'href': 'https://youtu.be/NOzCJa16gHw',
'link_text': 'https://youtu.be/NOzCJa16gHw'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.4 Computation with NumPy',
'href': 'https://youtu.be/QF9TQ9Yj6tc',
'link_text': 'https://youtu.be/QF9TQ9Yj6tc'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.5 Mutating NumPy Arrays',
'href': 'https://youtu.be/UPd2zcr5Tbc',
'link_text': 'https://youtu.be/UPd2zcr5Tbc'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.6 Plotting with Matplotlib',
'href': 'https://youtu.be/mRxAAcGRR2U',
'link_text': 'https://youtu.be/mRxAAcGRR2U'},
{'date': 'Sunday 7/28/2019 5:00 am',
'topic': '4.1.7 Intro to Pandas',
'href': 'https://youtu.be/zu4uCw79iRU',
'link_text': 'https://youtu.be/zu4uCw79iRU'},
{'date': 'Monday 7/29/2019 5:00 pm',
'topic': 'Office Hour 13',
'href': 'https://www.youtube.com/watch?v=yuZ58EYwfWc',
'link_text': 'https://www.youtube.com/watch?v=yuZ58EYwfWc'},
{'date': 'Tuesday 7/30/2019 9:00 pm',
'topic': 'Office Hour 14',
'href': 'https://www.youtube.com/watch?v=-1AitK6n2ts',
'link_text': 'https://www.youtube.com/watch?v=-1AitK6n2ts'},
{'date': 'Wednesday 7/31/2019 5:00 pm',
'topic': 'Office Hour 15',
'href': 'https://www.youtube.com/watch?v=Thi2X0AOaks',
'link_text': 'https://www.youtube.com/watch?v=Thi2X0AOaks'},
{'date': 'Thursday 8/1/2019 9:00 pm',
'topic': 'Office Hour 16',
'href': 'https://www.youtube.com/watch?v=cs5vMAjSaCI',
'link_text': 'https://www.youtube.com/watch?v=cs5vMAjSaCI'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.1 Pandas Overview',
'href': 'https://youtu.be/LLltyyJH9kk',
'link_text': 'https://youtu.be/LLltyyJH9kk'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.2 Pandas IO',
'href': 'https://youtu.be/KmmwUVrYMOQ',
'link_text': 'https://youtu.be/KmmwUVrYMOQ'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.3 Filtering DataFrames',
'href': 'https://youtu.be/EkCWEMe6cSg',
'link_text': 'https://youtu.be/EkCWEMe6cSg'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.4 Data Transformations',
'href': 'https://youtu.be/3HdYzqh8Bag',
'link_text': 'https://youtu.be/3HdYzqh8Bag'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.5 Data Aggregation',
'href': 'https://youtu.be/_93sDSezpD8',
'link_text': 'https://youtu.be/_93sDSezpD8'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.6 Joins & Multiple DataFrames',
'href': 'https://youtu.be/0QEgP-m8MFE',
'link_text': 'https://youtu.be/0QEgP-m8MFE'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.1.7 Time Series Data',
'href': 'https://youtu.be/WzIHzSet8WY',
'link_text': 'https://youtu.be/WzIHzSet8WY'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.1 Intro to Statistics',
'href': 'https://youtu.be/y54T0l8LilY',
'link_text': 'https://youtu.be/y54T0l8LilY'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.2 Estimating Means',
'href': 'https://youtu.be/qsDQHeqJuhw',
'link_text': 'https://youtu.be/qsDQHeqJuhw'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.3 Standard Error of the Mean',
'href': 'https://youtu.be/T_EC239eoM4',
'link_text': 'https://youtu.be/T_EC239eoM4'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.4 Hypothesis Testing & Z-Scores',
'href': 'https://youtu.be/FDOZK1DYh2w',
'link_text': 'https://youtu.be/FDOZK1DYh2w'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.2.5 Parameter Estimation & Confidence Intervals',
'href': 'https://youtu.be/W6fFG3x5-zE',
'link_text': 'https://youtu.be/W6fFG3x5-zE'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': '5.3.1 DW Miniproject Intro',
'href': 'https://youtu.be/xgna885PXg0',
'link_text': 'https://youtu.be/xgna885PXg0'},
{'date': 'Monday 8/5/2019 5:00 am',
'topic': 'Extra Statistics Videos',
'href': 'https://www.youtube.com/playlist?list=PLVNgHN883b8FuKC-Fpnh72thE4m7J1nNO',
'link_text': 'https://www.youtube.com/playlist?list=PLVNgHN883b8FuKC-Fpnh72thE4m7J1nNO'},
{'date': 'Monday 8/5/2019 5:00 pm',
'topic': 'Office Hour 17',
'href': 'canceled',
'link_text': 'canceled'},
{'date': 'Tuesday 8/6/2019 9:00 pm',
'topic': 'Office Hour 18',
'href': 'https://youtu.be/AyciFXagRbs',
'link_text': 'https://youtu.be/AyciFXagRbs'},
{'date': 'Wednesday 8/7/2019 5:00 pm',
'topic': 'Office Hour 19',
'href': 'https://www.youtube.com/watch?v=cju9Pk-3kAc',
'link_text': 'https://www.youtube.com/watch?v=cju9Pk-3kAc'},
{'date': 'Thursday 8/8/2019 9:00 pm',
'topic': 'Office Hour 20',
'href': 'https://www.youtube.com/watch?v=cSVde7bxMKg',
'link_text': 'https://www.youtube.com/watch?v=cSVde7bxMKg'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.1 Data Munging & Web Scraping',
'href': 'https://youtu.be/wV4BU2caSOs',
'link_text': 'https://youtu.be/wV4BU2caSOs'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.2 Cleaning & Structing Data',
'href': 'https://youtu.be/dtAEkwMUWZk',
'link_text': 'https://youtu.be/dtAEkwMUWZk'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.3 Dealing with Multiple Data Sources',
'href': 'https://youtu.be/ci9AvvnON4g',
'link_text': 'https://youtu.be/ci9AvvnON4g'},
{'date': 'Monday 8/12/2019 5:00 am',
'topic': '6.1.4 Data Munging in Pandas',
'href': 'https://youtu.be/1Y8e8UhsvME',
'link_text': 'https://youtu.be/1Y8e8UhsvME'},
{'date': 'Monday 8/12/2019 5:00 pm',
'topic': 'Office Hour 21',
'href': 'https://www.youtube.com/watch?v=KnOtFOARQ3w',
'link_text': 'https://www.youtube.com/watch?v=KnOtFOARQ3w'},
{'date': 'Tuesday 8/13/2019 9:00 pm',
'topic': 'Office Hour 22',
'href': 'https://www.youtube.com/watch?v=O9n6DY_fDXM',
'link_text': 'https://www.youtube.com/watch?v=O9n6DY_fDXM'},
{'date': 'Wednesday 8/14/2019 5:00 pm',
'topic': 'Office Hour 23',
'href': 'https://www.youtube.com/watch?v=bEv3mNfL_Ig',
'link_text': 'https://www.youtube.com/watch?v=bEv3mNfL_Ig'},
{'date': 'Thursday 8/15/2019 9:00 pm',
'topic': 'Office Hour 24',
'href': 'https://www.youtube.com/watch?v=IyjI7LfXyLE',
'link_text': 'https://www.youtube.com/watch?v=IyjI7LfXyLE'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.1 SQL & Relational Databases',
'href': 'https://youtu.be/1VkpuNpEqKA',
'link_text': 'https://youtu.be/1VkpuNpEqKA'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.2 Basic SQL Syntax',
'href': 'https://youtu.be/5i9OvFAPbAs',
'link_text': 'https://youtu.be/5i9OvFAPbAs'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.3 Filtering & Sorting Data in SQL',
'href': 'https://youtu.be/LEmp_AaIxGM',
'link_text': 'https://youtu.be/LEmp_AaIxGM'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.4 Joins & Aggregations in SQL',
'href': 'https://youtu.be/HLTotdjNvl4',
'link_text': 'https://youtu.be/HLTotdjNvl4'},
{'date': 'Monday 8/19/2019 5:00 am',
'topic': '7.1.5 Comparison of SQL Flavors',
'href': 'https://youtu.be/PeGsrKiJRY8',
'link_text': 'https://youtu.be/PeGsrKiJRY8'},
{'date': 'Monday 8/19/2019 5:00 pm',
'topic': 'Office Hour 25',
'href': 'https://youtu.be/GtbbTSAk3-k',
'link_text': 'https://youtu.be/GtbbTSAk3-k'},
{'date': 'Tuesday 8/20/2019 9:00 pm',
'topic': 'Office Hour 26',
'href': 'https://www.youtube.com/watch?v=obQjp9zaK4M',
'link_text': 'https://www.youtube.com/watch?v=obQjp9zaK4M'},
{'date': 'Wednesday 8/21/2019 5:00 pm',
'topic': 'Office Hour 27',
'href': 'https://www.youtube.com/watch?v=ZP-l-sSS-Uk',
'link_text': 'https://www.youtube.com/watch?v=ZP-l-sSS-Uk'},
{'date': 'Thursday 8/22/2019 9:00 pm',
'topic': 'Office Hour 28',
'href': 'https://www.youtube.com/watch?v=aILirNMlE38',
'link_text': 'https://www.youtube.com/watch?v=aILirNMlE38'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.1 Introduction to Object Relation Mapping',
'href': 'https://youtu.be/ZkOCn4FWd0Q',
'link_text': 'https://youtu.be/ZkOCn4FWd0Q'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.2 Using Classes for Applications',
'href': 'https://youtu.be/unLMZzFsx1Q',
'link_text': 'https://youtu.be/unLMZzFsx1Q'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.3 Translating Classes into SQL with ORM',
'href': 'https://youtu.be/ZT0gt0F88Ks',
'link_text': 'https://youtu.be/ZT0gt0F88Ks'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.1.4 Pushing Objects to SQL & Making Queries',
'href': 'https://youtu.be/88UKnoER9lw',
'link_text': 'https://youtu.be/88UKnoER9lw'},
{'date': 'Monday 8/26/2019 5:00 am',
'topic': '8.2.1 Course Conclusion',
'href': 'https://youtu.be/pAT_9CkcsU4',
'link_text': 'https://youtu.be/pAT_9CkcsU4'},
{'date': 'Monday 8/26/2019 5:00 pm',
'topic': 'Office Hour 29',
'href': 'https://www.youtube.com/watch?v=yptGfk0Lej8',
'link_text': 'https://www.youtube.com/watch?v=yptGfk0Lej8'},
{'date': 'Tuesday 8/27/2019 9:00 pm',
'topic': 'Office Hour 30',
'href': 'https://www.youtube.com/watch?v=GXNbrwYiEHg',
'link_text': 'https://www.youtube.com/watch?v=GXNbrwYiEHg'},
{'date': 'Wednesday 8/28/2019 5:00 pm',
'topic': 'Office Hour 31',
'href': 'https://www.youtube.com/watch?v=gU1rypGu_n4',
'link_text': 'https://www.youtube.com/watch?v=gU1rypGu_n4'},
{'date': 'Thursday 8/29/2019 9:00 pm',
'topic': 'Office Hour 32',
'href': 'https://www.youtube.com/watch?v=Ex2I9HnPZU8',
'link_text': 'https://www.youtube.com/watch?v=Ex2I9HnPZU8'}]

const emptyObj = [{
'date': '<<<<<<<<<<<<<<<<<<<<',
'topic': 'Unit 2 Machine Learning',
'href': '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>',
'link_text': '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
}];

const videoObjsMl = [{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': 'Introduction to Machine Learning',
'href': 'https://youtu.be/9J6FNvil6Gw',
'link_text': 'https://youtu.be/9J6FNvil6Gw'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.1 Intro to Scikit-learn',
'href': 'https://youtu.be/ecryKgFv5MA',
'link_text': 'https://youtu.be/ecryKgFv5MA'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.2 Predictors',
'href': 'https://youtu.be/AHALKrsFdVw',
'link_text': 'https://youtu.be/AHALKrsFdVw'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.3 Transformers and Pipelines',
'href': 'https://youtu.be/zVU4131QPsw',
'link_text': 'https://youtu.be/zVU4131QPsw'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.4 Feature Unions',
'href': 'https://youtu.be/_gOyCmdumps',
'link_text': 'https://youtu.be/_gOyCmdumps'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.5 Custom Transformers',
'href': 'https://youtu.be/I0YbI9x51kU',
'link_text': 'https://youtu.be/I0YbI9x51kU'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.6 Custom Predictors',
'href': 'https://youtu.be/bxf2JHcH4UI',
'link_text': 'https://youtu.be/bxf2JHcH4UI'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.7 Exercise Distance Transformer',
'href': 'https://youtu.be/0zYnOu1axGQ',
'link_text': 'https://youtu.be/0zYnOu1axGQ'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.2.8 Exercise Majority Classifier',
'href': 'https://youtu.be/SGLjDeJqDb0',
'link_text': 'https://youtu.be/SGLjDeJqDb0'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.3.1 Persisting Your Model',
'href': 'https://youtu.be/V9Pm_EZvABA',
'link_text': 'https://youtu.be/V9Pm_EZvABA'},
{'date': 'Monday 30-Sep-2019 5:00 am',
'topic': '1.3.2 Common Mistakes',
'href': 'https://youtu.be/YZQNIUIAi3A',
'link_text': 'https://youtu.be/YZQNIUIAi3A'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.1.1 Regression Metrics',
'href': 'https://youtu.be/wlMrMvphMuw',
'link_text': 'https://youtu.be/wlMrMvphMuw'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.2.1 Linear Regression Intro',
'href': 'https://youtu.be/L1h6cIG8XcA',
'link_text': 'https://youtu.be/L1h6cIG8XcA'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.2.2 Gradient Descent and Huber Loss',
'href': 'https://youtu.be/j0d4RogPiXM',
'link_text': 'https://youtu.be/j0d4RogPiXM'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.2.3 Multivariate Regression',
'href': 'https://youtu.be/9YZbXipwAQg',
'link_text': 'https://youtu.be/9YZbXipwAQg'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.2.4 Feature Importance',
'href': 'https://youtu.be/x5XB1ynjCGI',
'link_text': 'https://youtu.be/x5XB1ynjCGI'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.3.1 Classification Metrics',
'href': 'https://youtu.be/SMmbzWn8yGI',
'link_text': 'https://youtu.be/SMmbzWn8yGI'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.3.2 Probabilistic Models and Metrics',
'href': 'https://youtu.be/4MgWh8oD-hQ',
'link_text': 'https://youtu.be/4MgWh8oD-hQ'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.3.3 Logistic Regression',
'href': 'https://youtu.be/oqj-0_4WKq4',
'link_text': 'https://youtu.be/oqj-0_4WKq4'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.3.4 Multiclassification',
'href': 'https://youtu.be/gOVP8c1Cmmg',
'link_text': 'https://youtu.be/gOVP8c1Cmmg'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.4.1 Model Selection',
'href': 'https://youtu.be/lEBStVJXXpM',
'link_text': 'https://youtu.be/lEBStVJXXpM'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.4.2 Intro to Decision Trees',
'href': 'https://youtu.be/D6tNPIXCI1o',
'link_text': 'https://youtu.be/D6tNPIXCI1o'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.4.3 Underfitting and Overfitting',
'href': 'https://youtu.be/ZhhvoUAhA80',
'link_text': 'https://youtu.be/ZhhvoUAhA80'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.4.4 GridSearchCV',
'href': 'https://youtu.be/cWqE82yQi1Y',
'link_text': 'https://youtu.be/cWqE82yQi1Y'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.4.5 Comparing Two Models',
'href': 'https://youtu.be/rZ8XGPm-i1o',
'link_text': 'https://youtu.be/rZ8XGPm-i1o'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.5.1 Imputation',
'href': 'https://youtu.be/vJ3WBCW2sas',
'link_text': 'https://youtu.be/vJ3WBCW2sas'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.5.2 Categorical Data',
'href': 'https://youtu.be/qOAoV8HK8e0',
'link_text': 'https://youtu.be/qOAoV8HK8e0'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.6.1 GridsearchCV and Pipelines 1',
'href': 'https://youtu.be/c8ZJMXM6vvo',
'link_text': 'https://youtu.be/c8ZJMXM6vvo'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.6.2 GridsearchCV and Pipelines 2',
'href': 'https://youtu.be/mqnG1yANXvo',
'link_text': 'https://youtu.be/mqnG1yANXvo'},
{'date': 'Monday 7-Oct-2019 5:00 am',
'topic': '2.6.3 RandomizedSearchCV',
'href': 'https://youtu.be/BXzf0gJuV4w',
'link_text': 'https://youtu.be/BXzf0gJuV4w'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.1.1 Feature Engineering and Extraction',
'href': 'https://youtu.be/kHDRaKe2B5A',
'link_text': 'https://youtu.be/kHDRaKe2B5A'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.1.2 Feature Transformation',
'href': 'https://youtu.be/YAJsJNS3DAA',
'link_text': 'https://youtu.be/YAJsJNS3DAA'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.1.3 Curse of Dimensionality',
'href': 'https://youtu.be/HvG45qVJM84',
'link_text': 'https://youtu.be/HvG45qVJM84'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.1.4 Regularization',
'href': 'https://youtu.be/ArJqhJ415d4',
'link_text': 'https://youtu.be/ArJqhJ415d4'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.1.5 Multicollinearity and PCA',
'href': 'https://youtu.be/8eBKta-D334',
'link_text': 'https://youtu.be/8eBKta-D334'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.1.6 Ensemble Models',
'href': 'https://youtu.be/oUOi5T1b_iU',
'link_text': 'https://youtu.be/oUOi5T1b_iU'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.2.1 Bias and Variance',
'href': 'https://youtu.be/-ZLg6Zp9HHg',
'link_text': 'https://youtu.be/-ZLg6Zp9HHg'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.2.2 Learning Curves',
'href': 'https://youtu.be/KB4fPj68Rbo',
'link_text': 'https://youtu.be/KB4fPj68Rbo'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.3.1 Intro KNN',
'href': 'https://youtu.be/EV6xlHdTaEY',
'link_text': 'https://youtu.be/EV6xlHdTaEY'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.3.2 KNN Bias and Variance',
'href': 'https://youtu.be/AXbhiyWJZdw',
'link_text': 'https://youtu.be/AXbhiyWJZdw'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.3.3 KNN Time Complexity',
'href': 'https://youtu.be/XleyueB7jXU',
'link_text': 'https://youtu.be/XleyueB7jXU'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.3.4 KD Trees and Weights',
'href': 'https://youtu.be/UV1WeqUFPE8',
'link_text': 'https://youtu.be/UV1WeqUFPE8'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.1 Intro to NLP',
'href': 'https://youtu.be/w3HtykbMcqk',
'link_text': 'https://youtu.be/w3HtykbMcqk'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.2 Spacy',
'href': 'https://youtu.be/7nojkNN0EME',
'link_text': 'https://youtu.be/7nojkNN0EME'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.3 Obtaining a Corpus',
'href': 'https://youtu.be/4mYBqqbW408',
'link_text': 'https://youtu.be/4mYBqqbW408'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.4 Bag of Words Model',
'href': 'https://youtu.be/7bKNknkmIJI',
'link_text': 'https://youtu.be/7bKNknkmIJI'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.5 Hashing Vectorizer',
'href': 'https://youtu.be/_wPHgQhiMVY',
'link_text': 'https://youtu.be/_wPHgQhiMVY'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.6 TF-IDF',
'href': 'https://youtu.be/kv9cE-uOnis',
'link_text': 'https://youtu.be/kv9cE-uOnis'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.7 Improving Signal',
'href': 'https://youtu.be/UR4JcVOBiAI',
'link_text': 'https://youtu.be/UR4JcVOBiAI'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.8 N-grams and Similarity',
'href': 'https://youtu.be/tuwCNPEFRDs',
'link_text': 'https://youtu.be/tuwCNPEFRDs'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.9 Word Usage Classifier',
'href': 'https://youtu.be/FNU4dNeKrHo',
'link_text': 'https://youtu.be/FNU4dNeKrHo'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.10 Exercise I',
'href': 'https://youtu.be/kAZuP3efPbg',
'link_text': 'https://youtu.be/kAZuP3efPbg'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.11 Exercise II',
'href': 'https://youtu.be/MkpFJkSrC2o',
'link_text': 'https://youtu.be/MkpFJkSrC2o'},
{'date': 'Monday 14-Oct-2019 5:00 am',
'topic': '3.4.12 Exercise III and IV',
'href': 'https://youtu.be/Uw1_iZgihC0',
'link_text': 'https://youtu.be/Uw1_iZgihC0'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.1 Intro to Decision Trees',
'href': 'https://youtu.be/4cIr8W9tXD8',
'link_text': 'https://youtu.be/4cIr8W9tXD8'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.2 Tree Error Metrics',
'href': 'https://youtu.be/Pv8bnN3E4xA',
'link_text': 'https://youtu.be/Pv8bnN3E4xA'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.3 Trees for Regression',
'href': 'https://youtu.be/LvUazyMSRFM',
'link_text': 'https://youtu.be/LvUazyMSRFM'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.4 Training Trees and Hyperparameters',
'href': 'https://youtu.be/nC-pHG_hgdY',
'link_text': 'https://youtu.be/nC-pHG_hgdY'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.5 Geometric Interpretation and Time Complexity',
'href': 'https://youtu.be/l23BnV-4Xwc',
'link_text': 'https://youtu.be/l23BnV-4Xwc'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.6 Time Complexity Continued',
'href': 'https://youtu.be/oD_INvReM_I',
'link_text': 'https://youtu.be/oD_INvReM_I'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.7 Random Forests',
'href': 'https://youtu.be/JUzss0-pvz8',
'link_text': 'https://youtu.be/JUzss0-pvz8'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.8 Extreme Random Forests',
'href': 'https://youtu.be/GLjopN8Lw94',
'link_text': 'https://youtu.be/GLjopN8Lw94'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.9 Gradient Boosting Trees I',
'href': 'https://youtu.be/KJtV7fTrFH4',
'link_text': 'https://youtu.be/KJtV7fTrFH4'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.10 Gradient Boosting Trees II',
'href': 'https://youtu.be/E2R4D2Gc4x4',
'link_text': 'https://youtu.be/E2R4D2Gc4x4'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.11 Feature Importance',
'href': 'https://youtu.be/WDLvgw-Znmg',
'link_text': 'https://youtu.be/WDLvgw-Znmg'},
{'date': 'Monday 21-Oct-2019 5:00 am',
'topic': '4.1.12 Exercises',
'href': 'https://youtu.be/7q3pk2VcDFQ',
'link_text': 'https://youtu.be/7q3pk2VcDFQ'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.1 Intro to SVM',
'href': 'https://youtu.be/GxSSq1B-BHg',
'link_text': 'https://youtu.be/GxSSq1B-BHg'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.2 Largest Margin Classifier',
'href': 'https://youtu.be/EK-69gK8y9E',
'link_text': 'https://youtu.be/EK-69gK8y9E'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.3 Soft Margin Classifier',
'href': 'https://youtu.be/QT-Flust1Hc',
'link_text': 'https://youtu.be/QT-Flust1Hc'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.4 SVM Kernels',
'href': 'https://youtu.be/VQWkkPV1Q_Q',
'link_text': 'https://youtu.be/VQWkkPV1Q_Q'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.5 SVM vs Logistic Regression',
'href': 'https://youtu.be/4G7uEZCAr2U',
'link_text': 'https://youtu.be/4G7uEZCAr2U'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.6 SVM Regression',
'href': 'https://youtu.be/xp8TJgzgWp0',
'link_text': 'https://youtu.be/xp8TJgzgWp0'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.7 SVM Lagrangian Dual',
'href': 'https://youtu.be/defq3yJ8cyw',
'link_text': 'https://youtu.be/defq3yJ8cyw'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.8 Kernel Trick',
'href': 'https://youtu.be/YcRcxm4LSqg',
'link_text': 'https://youtu.be/YcRcxm4LSqg'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.9 SVM Time Complexity and Multiclass',
'href': 'https://youtu.be/FR5D4A3Nn0c',
'link_text': 'https://youtu.be/FR5D4A3Nn0c'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.10 SVM Tuning Kernels Exercise Part I',
'href': 'https://youtu.be/MggSYvtMcLQ',
'link_text': 'https://youtu.be/MggSYvtMcLQ'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.11 SVM Tuning Kernels Exercise Part II',
'href': 'https://youtu.be/tvWb6XObsFg',
'link_text': 'https://youtu.be/tvWb6XObsFg'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.12 SVM Kernel Approximations',
'href': 'https://youtu.be/A3HPwA0IWIM',
'link_text': 'https://youtu.be/A3HPwA0IWIM'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.13 SVM Online Learning',
'href': 'https://youtu.be/bgzt8UL8x4Y',
'link_text': 'https://youtu.be/bgzt8UL8x4Y'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.1.14 SVM Online Learning Pipeline',
'href': 'https://youtu.be/E1RoFHjJRDc',
'link_text': 'https://youtu.be/E1RoFHjJRDc'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.1 Intro to Clustering',
'href': 'https://youtu.be/HktZtB7Te0c',
'link_text': 'https://youtu.be/HktZtB7Te0c'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.2 Metrics for Clustering',
'href': 'https://youtu.be/kWsylUt8LxA',
'link_text': 'https://youtu.be/kWsylUt8LxA'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.3 KMeans Clustering',
'href': 'https://youtu.be/_OKUAiC9FLY',
'link_text': 'https://youtu.be/_OKUAiC9FLY'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.4 Elbow Plots',
'href': 'https://youtu.be/J_jH7cXGUSQ',
'link_text': 'https://youtu.be/J_jH7cXGUSQ'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.5 Gaussian Mixture Models',
'href': 'https://youtu.be/WwDiKfHW52U',
'link_text': 'https://youtu.be/WwDiKfHW52U'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.6 Choosing Cluster Based on Silhouette',
'href': 'https://youtu.be/Gj4HHh4dDEk',
'link_text': 'https://youtu.be/Gj4HHh4dDEk'},
{'date': 'Tuesday 29-Oct-2019 5:00 am',
'topic': '5.2.7 GMM Choosing Number of Components',
'href': 'https://youtu.be/QO3F4lBs4m4',
'link_text': 'https://youtu.be/QO3F4lBs4m4'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.1 Intro to Time Series',
'href': 'https://youtu.be/BvDcWoLnWFk',
'link_text': 'https://youtu.be/BvDcWoLnWFk'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.2 Crossvalidation in Time Series',
'href': 'https://youtu.be/ZOJAof-3YYA',
'link_text': 'https://youtu.be/ZOJAof-3YYA'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.3 Stationary Signal',
'href': 'https://youtu.be/WytJdsQBeos',
'link_text': 'https://youtu.be/WytJdsQBeos'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.4 Modeling Drift',
'href': 'https://youtu.be/53FLb9usJBk',
'link_text': 'https://youtu.be/53FLb9usJBk'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.5 Fourier Transforms Part I',
'href': 'https://youtu.be/k-cF7LB7p4w',
'link_text': 'https://youtu.be/k-cF7LB7p4w'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.6 Fourier Transforms Part II',
'href': 'https://youtu.be/7KSdhV2elq8',
'link_text': 'https://youtu.be/7KSdhV2elq8'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.7 Fourier Components in our Model',
'href': 'https://youtu.be/ek3vt4xLL-k',
'link_text': 'https://youtu.be/ek3vt4xLL-k'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.8 Modeling Noise',
'href': 'https://youtu.be/IBBcCxCPv1w',
'link_text': 'https://youtu.be/IBBcCxCPv1w'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.9 Moving Statistics',
'href': 'https://youtu.be/8LUt3PBcCFk',
'link_text': 'https://youtu.be/8LUt3PBcCFk'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.10 Full Model',
'href': 'https://youtu.be/oIIE1Fh8eNc',
'link_text': 'https://youtu.be/oIIE1Fh8eNc'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.11 ARMA and ARIMA',
'href': 'https://youtu.be/UPox0nn4IvE',
'link_text': 'https://youtu.be/UPox0nn4IvE'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.1.12 AR Example',
'href': 'https://youtu.be/GaQ70ZHo69s',
'link_text': 'https://youtu.be/GaQ70ZHo69s'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.1 Intro to Dimension Reduction',
'href': 'https://youtu.be/b5BihaS90q0',
'link_text': 'https://youtu.be/b5BihaS90q0'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.2 Math of Projections',
'href': 'https://youtu.be/CZjSrCpkxxk',
'link_text': 'https://youtu.be/CZjSrCpkxxk'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.3 PCA',
'href': 'https://youtu.be/dCYH6MVyfSA',
'link_text': 'https://youtu.be/dCYH6MVyfSA'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.4 PCA in Scikit Learn',
'href': 'https://youtu.be/lSxcJbaRvkA',
'link_text': 'https://youtu.be/lSxcJbaRvkA'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.5 PCA Implementation Details',
'href': 'https://youtu.be/QQl4h1gyCwc',
'link_text': 'https://youtu.be/QQl4h1gyCwc'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.6 Choosing the Number of Components',
'href': 'https://youtu.be/4azFI2QzyXU',
'link_text': 'https://youtu.be/4azFI2QzyXU'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.7 Truncated SVD',
'href': 'https://youtu.be/nfwInvCoym0',
'link_text': 'https://youtu.be/nfwInvCoym0'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.8 NMF',
'href': 'https://youtu.be/ELLDyWiiSXU',
'link_text': 'https://youtu.be/ELLDyWiiSXU'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.9 Using PCA with Supervised ML',
'href': 'https://youtu.be/u8tUlG28CH0',
'link_text': 'https://youtu.be/u8tUlG28CH0'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.10 PCA for Visualization',
'href': 'https://youtu.be/MRwKUI5ulio',
'link_text': 'https://youtu.be/MRwKUI5ulio'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.11 NMF Exercise Part I',
'href': 'https://youtu.be/oo1sDDHE-DM',
'link_text': 'https://youtu.be/oo1sDDHE-DM'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.12 NMF Exercise Part II',
'href': 'https://youtu.be/PQt9XPS_bT0',
'link_text': 'https://youtu.be/PQt9XPS_bT0'},
{'date': 'Monday 4-Nov-2019 6:00 am',
'topic': '6.2.13 Variants of PCA',
'href': 'https://youtu.be/0KdHFPXsonE',
'link_text': 'https://youtu.be/0KdHFPXsonE'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.1 Intro to Anomaly Detection',
'href': 'https://youtu.be/KuFUQ7wWhsY',
'link_text': 'https://youtu.be/KuFUQ7wWhsY'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.2 One class SVM',
'href': 'https://youtu.be/2l0TD7gCzvQ',
'link_text': 'https://youtu.be/2l0TD7gCzvQ'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.3 Isolation Forest',
'href': 'https://youtu.be/xIAwOj_xh9s',
'link_text': 'https://youtu.be/xIAwOj_xh9s'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.4 Comparison Between One-class SVM and Isolation Forest',
'href': 'https://youtu.be/VIyK4gLB2hg',
'link_text': 'https://youtu.be/VIyK4gLB2hg'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.5 Intro to Case Study',
'href': 'https://youtu.be/TQk9uSFMo6w',
'link_text': 'https://youtu.be/TQk9uSFMo6w'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.6 Initial Baseline Model Part I',
'href': 'https://youtu.be/qrJTbKyv1eA',
'link_text': 'https://youtu.be/qrJTbKyv1eA'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.7 Initial Baseline model Part II',
'href': 'https://youtu.be/HMRoWtI6eMo',
'link_text': 'https://youtu.be/HMRoWtI6eMo'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.8 Full Baseline Model',
'href': 'https://youtu.be/gTyO2ldQfWc',
'link_text': 'https://youtu.be/gTyO2ldQfWc'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.9 Z-score Detection',
'href': 'https://youtu.be/d2YIby-isCE',
'link_text': 'https://youtu.be/d2YIby-isCE'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.10 Rolling Z-score Detection',
'href': 'https://youtu.be/cQ2YIZmeQKg',
'link_text': 'https://youtu.be/cQ2YIZmeQKg'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.11 Using External Features Initial Model',
'href': 'https://youtu.be/_SvveHx_Nfk',
'link_text': 'https://youtu.be/_SvveHx_Nfk'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.12 Using External Features Tuning the Model',
'href': 'https://youtu.be/2Z5SQsx4LFE',
'link_text': 'https://youtu.be/2Z5SQsx4LFE'},
{'date': 'Monday 11-Nov-2019 6:00 am',
'topic': '7.1.13 Packaging the Time Series Anomaly Detector',
'href': 'https://youtu.be/hTWHZTTbmJk',
'link_text': 'https://youtu.be/hTWHZTTbmJk'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.1 Model Considerations',
'href': 'https://youtu.be/SFFFnqugdOQ',
'link_text': 'https://youtu.be/SFFFnqugdOQ'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.2 Model Development',
'href': 'https://youtu.be/DrClE-USVDg',
'link_text': 'https://youtu.be/DrClE-USVDg'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.3 Flask App Local Development',
'href': 'https://youtu.be/chRA6Lngw-A',
'link_text': 'https://youtu.be/chRA6Lngw-A'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.4 GET requests',
'href': 'https://youtu.be/v1yYLbB_uUE',
'link_text': 'https://youtu.be/v1yYLbB_uUE'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.5 Making GET Requests with Model',
'href': 'https://youtu.be/q9DgF7mJbrc',
'link_text': 'https://youtu.be/q9DgF7mJbrc'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.6 Using our Model with Twitter Web API',
'href': 'https://youtu.be/AFwGAeBDeEk',
'link_text': 'https://youtu.be/AFwGAeBDeEk'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.7 POST Requests and Flask Templates',
'href': 'https://youtu.be/qbi3aT0KEsA',
'link_text': 'https://youtu.be/qbi3aT0KEsA'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.8 Preparing for Deployment to the Web',
'href': 'https://youtu.be/zqbIVwnA0go',
'link_text': 'https://youtu.be/zqbIVwnA0go'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.1.9 Deploying our App to the Web with Heroku',
'href': 'https://youtu.be/ALlhG0pjx1w',
'link_text': 'https://youtu.be/ALlhG0pjx1w'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.2.1 Rethinking Model Tuning',
'href': 'https://youtu.be/TPcytvHTQoA',
'link_text': 'https://youtu.be/TPcytvHTQoA'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.2.2 Intro to Bayes Theorem',
'href': 'https://youtu.be/bzsLD59kF2g',
'link_text': 'https://youtu.be/bzsLD59kF2g'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.2.3 Bayesian Inference',
'href': 'https://youtu.be/i6EyxNl_mdk',
'link_text': 'https://youtu.be/i6EyxNl_mdk'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.2.4 Bayesian Optimization',
'href': 'https://youtu.be/GIQL38tkyRs',
'link_text': 'https://youtu.be/GIQL38tkyRs'},
{'date': 'Monday 18-Nov-2019 6:00 am',
'topic': '8.3.1 End of Course Material',
'href': 'https://youtu.be/htdGrsIMZkg',
'link_text': 'https://youtu.be/htdGrsIMZkg'},
{'date': 'Monday 18-Nov-2019 10:00 pm',
'topic': 'Office Hour 29',
'href': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live',
'link_text': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live'},
{'date': 'Tuesday 19-Nov-2019 6:00 pm',
'topic': 'Office Hour 30',
'href': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live',
'link_text': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live'},
{'date': 'Wednesday 20-Nov-2019 10:00 pm',
'topic': 'Office Hour 31',
'href': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live',
'link_text': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live'},
{'date': 'Thursday 21-Nov-2019 6:00 pm',
'topic': 'Office Hour 32',
'href': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live',
'link_text': 'https://www.youtube.com/channel/UCW5qH1I2RMA0CnJ0uo7OTvQ/live'},
{'date': 'Friday 22-Nov-2019 6:00 am',
'topic': 'PAST OFFICE HOURS PLAYLIST',
'href': 'https://www.youtube.com/playlist?list=PLeDYvCW3J3jm9MQAZaUjvXvV_kaQQmr2m',
'link_text': 'https://www.youtube.com/playlist?list=PLeDYvCW3J3jm9MQAZaUjvXvV_kaQQmr2m'}];

videoObjs = videoObjs.concat(emptyObj)
videoObjs = videoObjs.concat(videoObjsMl)
const table = document.createElement('table');
table.style.border = '1px solid';

table.style.borderCollapse = 'collapse';
const contents = document.getElementById('content');
const row = document.createElement('tr');
row.style.backgroundColor = 'darkgreen'
row.style.color = 'white';
for (field of ['Date', 'Event', 'Youtube Link']) {
  const header = document.createElement('th');
  header.style.height = '40px';
  header.innerHTML = field;
  row.appendChild(header)
}

const footerRow = document.createElement('tr');
footerRow.style.backgroundColor = 'darkgreen'
for (field of ['Date', 'Event', 'Youtube Link']) {
  const footer = document.createElement('th');
  footer.style.height = '40px';
  footer.innerHTML = '';
  footerRow.appendChild(footer)
}

table.appendChild(row);
for (i of videoObjs) {
  const rows = document.createElement('tr');
  const fields = Object.keys(i);

  // remove the link_text field
  fields.pop()
  fields.forEach(key => {
    const cell = document.createElement('td');
    cell.style.border = '1px solid';
    cell.style.padding = '5px';
    if (key === 'href') {
      const anchor = document.createElement('a');
      anchor.innerHTML = i[key];
      anchor.href = i['href'];
      anchor.target = '_blank';
      cell.appendChild(anchor);
      anchor.style.color = 'white';
    } else {
      cell.innerHTML = i[key]
    }
    cell.style.backgroundColor = 'gray'
    cell.style.color = 'white';
    rows.appendChild(cell);
  })
  table.appendChild(rows)
};

table.appendChild(footerRow)
contents.appendChild(table);
